Repository dpplanner/app, pull requests merged in 2024-02, with the labels that each got.

#19 PR : 클럽 예약 시간표 구현 (#18)
  dplanner/assets/images/showmodal_scrollcontrolbar.png
  dplanner/lib/club_root_page.dart
  dplanner/lib/controllers/club.dart
  dplanner/lib/controllers/item.dart
  dplanner/lib/main.dart
  dplanner/lib/pages/club_timetable_page.dart
  dplanner/pubspec.yaml
Labels: feat

#21 PR : 클럽 게시판 UI 구현 (#20)
  dplanner/assets/images/comment_line.png
  dplanner/assets/images/comment_line.svg
  dplanner/assets/images/jin_profile.png
  dplanner/assets/images/notification_icon/icon_accept.svg
  dplanner/assets/images/notification_icon/icon_invite.svg
  dplanner/assets/images/notification_icon/icon_notice.svg
  dplanner/assets/images/notification_icon/icon_reject.svg
  dplanner/assets/images/notification_icon/icon_report.svg
  dplanner/assets/images/notification_icon/icon_request.svg
  dplanner/assets/images/post_add_photo.svg
  dplanner/assets/images/showmodal_scrollcontrolbar.png
  dplanner/assets/images/showmodal_scrollcontrolbar.svg
  dplanner/lib/club_root_page.dart
  dplanner/lib/pages/club_create_page.dart
  dplanner/lib/pages/club_create_success_next_page.dart
  dplanner/lib/pages/club_home_page.dart
  dplanner/lib/pages/club_join_next_page.dart
  dplanner/lib/pages/club_join_page.dart
  dplanner/lib/pages/club_join_success_page.dart
  dplanner/lib/pages/club_my_page.dart
  dplanner/lib/pages/club_timetable_page.dart
  dplanner/lib/pages/notification_page.dart
  dplanner/lib/pages/post_add_page.dart
  dplanner/lib/pages/post_page.dart
  dplanner/lib/routes.dart
  dplanner/lib/widgets/bottom_bar.dart
  dplanner/lib/widgets/club_card.dart
  dplanner/lib/widgets/nextpage_button.dart
  dplanner/lib/widgets/notification_card.dart
  dplanner/lib/widgets/outline_textform.dart
  dplanner/lib/widgets/post_card.dart
  dplanner/lib/widgets/post_comment.dart
  dplanner/lib/widgets/post_content.dart
  dplanner/lib/widgets/underline_textform.dart
  dplanner/pubspec.yaml
Labels: feat

#23 PR : 마이페이지 UI 구현 (#22)
  dplanner/assets/images/dancepozz_big_logo.png
  dplanner/assets/images/dancepozz_logo.svg
  dplanner/assets/images/icon_naver.svg
  dplanner/lib/pages/app_setting_page.dart
  dplanner/lib/pages/club_home_page.dart
  dplanner/lib/pages/club_info_page.dart
  dplanner/lib/pages/club_member_list_page.dart
  dplanner/lib/pages/club_my_page.dart
  dplanner/lib/pages/club_timetable_page.dart
  dplanner/lib/pages/my_activity_check_page.dart
  dplanner/lib/pages/my_profile_modification_page.dart
  dplanner/lib/pages/reservation_list_page.dart
  dplanner/lib/pages/resource_list_page.dart
  dplanner/lib/style.dart
  dplanner/lib/widgets/club_member_card.dart
  dplanner/lib/widgets/notification_card.dart
  dplanner/lib/widgets/post_mini_card.dart
  dplanner/lib/widgets/reservation_big_card.dart
  dplanner/lib/widgets/reservation_mini_card.dart
  dplanner/lib/widgets/resource_card.dart
  dplanner/lib/widgets/underline_textform.dart
  dplanner/pubspec.yaml
Labels: feat

#25 PR : Firebase 연동 (#24)
  dplanner/android/app/google-services.json
  dplanner/ios/Runner/GoogleService-Info.plist
  dplanner/ios/firebase_app_id_file.json
  dplanner/lib/firebase_options.dart
  dplanner/lib/main.dart
  dplanner/lib/pages/club_create_page.dart
  dplanner/lib/pages/club_join_next_page.dart
  dplanner/lib/pages/club_timetable_page.dart
  dplanner/lib/widgets/club_member_card.dart
  dplanner/lib/widgets/nextpage_button.dart
  dplanner/lib/widgets/resource_card.dart
  dplanner/pubspec.yaml
Labels: feat

#28 PR : Firebase 연동한 메일 변경 완료 (#27)
  dplanner/android/app/google-services.json
  dplanner/lib/firebase_options.dart
Labels: fix

#29 PR : 소셜 로그인 구현 (#26)
  dplanner/android/app/build.gradle
  dplanner/android/app/google-services.json
  dplanner/android/app/src/main/AndroidManifest.xml
  dplanner/android/app/src/main/res/values/strings.xml
  dplanner/android/build.gradle
  dplanner/android/settings.gradle
  dplanner/lib/const.dart
  dplanner/lib/controllers/login.dart
  dplanner/lib/main.dart
  dplanner/lib/models/token_model.dart
  dplanner/lib/models/user_model.dart
  dplanner/lib/pages/club_my_page.dart
  dplanner/lib/pages/login_page.dart
  dplanner/lib/services/user_api_service.dart
  dplanner/pubspec.yaml
Labels: feat

#39 PR : iOS 로그인 - 네이버 (#38)
  dplanner/ios/Flutter/AppFrameworkInfo.plist
  dplanner/ios/Flutter/Debug.xcconfig
  dplanner/ios/Flutter/Release.xcconfig
  dplanner/ios/Podfile
  dplanner/ios/Podfile.lock
  dplanner/ios/Runner.xcodeproj/project.pbxproj
  dplanner/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  dplanner/ios/Runner.xcworkspace/contents.xcworkspacedata
  dplanner/ios/Runner/AppDelegate.swift
  dplanner/ios/Runner/Info.plist
Labels: feat

#45 PR : 로그인 후 페이지 전환 (#44)
  dplanner/lib/pages/login_page.dart
Labels: fix

#47 PR : 로그인 시 필요 데이터 저장 (#46)
  dplanner/lib/controllers/member.dart
  dplanner/lib/models/club_member_model.dart
  dplanner/lib/pages/club_home_page.dart
  dplanner/lib/pages/club_join_next_page.dart
  dplanner/lib/pages/login_page.dart
  dplanner/lib/services/club_api_service.dart
  dplanner/lib/services/club_member_api_service.dart
  dplanner/lib/services/token_api_service.dart
  dplanner/lib/widgets/club_card.dart
Labels: feat

#49 PR : 실제 데이터 UI 적용 (#48)
  dplanner/lib/const.dart
  dplanner/lib/controllers/login.dart
  dplanner/lib/main.dart
  dplanner/lib/models/token_model.dart
  dplanner/lib/models/user_model.dart
  dplanner/lib/pages/app_setting_page.dart
  dplanner/lib/pages/club_home_page.dart
  dplanner/lib/pages/club_info_page.dart
  dplanner/lib/pages/club_my_page.dart
  dplanner/lib/pages/club_timetable_page.dart
  dplanner/lib/pages/login_page.dart
  dplanner/lib/pages/my_profile_modification_page.dart
  dplanner/lib/services/club_member_api_service.dart
  dplanner/lib/services/token_api_service.dart
Labels: feat, refactor
