Repository dpplanner/app, pull requests merged in 2024-04, with the labels that each got.

#72 PR : 게시판 수정사항 적용 - 2 (#65)
  dplanner/ios/Podfile.lock
  dplanner/lib/models/post_comment_model.dart
  dplanner/lib/pages/club_home_page.dart
  dplanner/lib/pages/my_activity_check_page.dart
  dplanner/lib/pages/post_page.dart
  dplanner/lib/services/club_post_api_service.dart
  dplanner/lib/widgets/comment_mini_card.dart
  dplanner/lib/widgets/post_card.dart
  dplanner/lib/widgets/post_comment.dart
  dplanner/lib/widgets/post_content.dart
Labels: feat, refactor, design

#75 PR : 64 애플 로그인 구현 - 2(#64)
  dplanner/lib/pages/login_page.dart
Labels: design

#76 PR : 예약 시간표 기능 정리 (#71)
  dplanner/lib/models/reservation_model.dart
  dplanner/lib/pages/club_my_page.dart
  dplanner/lib/pages/club_timetable_page.dart
  dplanner/lib/widgets/reservation_admin_card.dart
Labels: feat, fix

#78 PR : 게시판 수정사항 적용 - 3 (#65)
  dplanner/lib/pages/post_page.dart
  dplanner/lib/widgets/post_card.dart
  dplanner/lib/widgets/post_content.dart
Labels: refactor, design

#83 PR : 프로필 사진 변경 에러 해결 (#82)
  dplanner/lib/pages/club_setting_page.dart
  dplanner/lib/pages/my_profile_modification_page.dart
Labels: refactor
